name: Update apps

on:
  workflow_dispatch:
jobs:
  update-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: jdx/mise-action@v3
      - uses: nanasess/setup-chromedriver@v2
      - name: Fetch and patch apks
        run: uv run --with . repatcher patch-all

      - name: Make a folder where I put the apks
        run: |
          mkdir -p /tmp/RESULT
          mv /tmp/revancedbot/patched_apks/*.apk /tmp/RESULT

      - name: Upload APKs as GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: /tmp/RESULT

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: update-apps
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
