name: Update apps

on:
  workflow_dispatch:
jobs:
  update-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
      - uses: nanasess/setup-chromedriver@v2
      - name: Fetch and patch apks
        run: uv run --with . repatcher patch-all

      - name: Make a folder where I put the apks
        run: |
          mkdir -p /tmp/RESULT
          mv /tmp/revancedbot/patched_apks/*.apk /tmp/RESULT

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/RESULT
