name: Update apps

on:
  workflow_dispatch:
jobs:
  update-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: jdx/mise-action@v3
      - uses: nanasess/setup-chromedriver@v2
      - name: Fetch and patch apks
        run: uv run --with . repatcher patch-all

      - name: Make a folder where I put the apks
        run: |
          mkdir -p /tmp/RESULT
          mv /tmp/revancedbot/patched_apks/*.apk /tmp/RESULT

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/RESULT
